import type { Book } from "./types"

// Generate random book data
export const books: Book[] = [
  {
    id: "1",
    title: "The Midnight Library",
    author: "Matt Haig",
    description:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices... Would you have done anything different, if you had the chance to undo your regrets?",
    price: 14.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Fiction",
    rating: 4,
    reviews: 1289,
    publisher: "Viking",
    publicationDate: "August 13, 2020",
    pages: 304,
    language: "English",
    inStock: true,
  },
  {
    id: "2",
    title: "Atomic Habits",
    author: "James Clear",
    description:
      "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    price: 11.98,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Self-Help",
    rating: 5,
    reviews: 2547,
    publisher: "Avery",
    publicationDate: "October 16, 2018",
    pages: 320,
    language: "English",
    inStock: true,
  },
  {
    id: "3",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description:
      "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas. One evening her husband Gabriel returns home late from a fashion shoot, and Alicia shoots him five times in the face, and then never speaks another word.",
    price: 12.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Thriller",
    rating: 4,
    reviews: 1876,
    publisher: "Celadon Books",
    publicationDate: "February 5, 2019",
    pages: 336,
    language: "English",
    inStock: true,
  },
  {
    id: "4",
    title: "Educated",
    author: "Tara Westover",
    description:
      "Born to survivalists in the mountains of Idaho, Tara Westover was seventeen the first time she set foot in a classroom. Her family was so isolated from mainstream society that there was no one to ensure the children received an education, and no one to intervene when one of Tara's older brothers became violent.",
    price: 13.69,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Memoir",
    rating: 5,
    reviews: 2103,
    publisher: "Random House",
    publicationDate: "February 20, 2018",
    pages: 352,
    language: "English",
    inStock: true,
  },
  {
    id: "5",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    description:
      "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl. But Kya is not what they say.",
    price: 9.98,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Fiction",
    rating: 4,
    reviews: 3254,
    publisher: "G.P. Putnam's Sons",
    publicationDate: "August 14, 2018",
    pages: 384,
    language: "English",
    inStock: true,
  },
  {
    id: "6",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    description:
      "Doing well with money isn't necessarily about what you know. It's about how you behave. And behavior is hard to teach, even to really smart people. Money—investing, personal finance, and business decisions—is typically taught as a math-based field, where data and formulas tell us exactly what to do.",
    price: 10.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Finance",
    rating: 5,
    reviews: 1543,
    publisher: "Harriman House",
    publicationDate: "September 8, 2020",
    pages: 256,
    language: "English",
    inStock: true,
  },
  {
    id: "7",
    title: "The Alchemist",
    author: "Paulo Coelho",
    description:
      "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.",
    price: 8.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Fiction",
    rating: 5,
    reviews: 4321,
    publisher: "HarperOne",
    publicationDate: "April 25, 1993",
    pages: 208,
    language: "English",
    inStock: true,
  },
  {
    id: "8",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    description:
      "From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution—a #1 international bestseller—that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be 'human.'",
    price: 15.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "History",
    rating: 4,
    reviews: 2876,
    publisher: "Harper",
    publicationDate: "February 10, 2015",
    pages: 464,
    language: "English",
    inStock: true,
  },
  {
    id: "9",
    title: "The Four Winds",
    author: "Kristin Hannah",
    description:
      "Texas, 1934. Millions are out of work and a drought has broken the Great Plains. Farmers are fighting to keep their land and their livelihoods as the crops are failing, the water is drying up, and dust threatens to bury them all.",
    price: 14.49,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Historical Fiction",
    rating: 4,
    reviews: 1432,
    publisher: "St. Martin's Press",
    publicationDate: "February 2, 2021",
    pages: 464,
    language: "English",
    inStock: true,
  },
  {
    id: "10",
    title: "Project Hail Mary",
    author: "Andy Weir",
    description:
      "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish. Except that right now, he doesn't know that. He can't even remember his own name, let alone the nature of his assignment or how to complete it.",
    price: 16.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Science Fiction",
    rating: 5,
    reviews: 987,
    publisher: "Ballantine Books",
    publicationDate: "May 4, 2021",
    pages: 496,
    language: "English",
    inStock: true,
  },
  {
    id: "11",
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    description:
      "A Life No One Will Remember. A Story You Will Never Forget. France, 1714: in a moment of desperation, a young woman makes a Faustian bargain to live forever—and is cursed to be forgotten by everyone she meets.",
    price: 13.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Fantasy",
    rating: 4,
    reviews: 1654,
    publisher: "Tor Books",
    publicationDate: "October 6, 2020",
    pages: 448,
    language: "English",
    inStock: true,
  },
  {
    id: "12",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    description:
      "From the bestselling and Booker Prize winning author of Never Let Me Go and The Remains of the Day, a stunning new novel that asks, what does it mean to love?",
    price: 15.49,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "Literary Fiction",
    rating: 4,
    reviews: 876,
    publisher: "Knopf",
    publicationDate: "March 2, 2021",
    pages: 320,
    language: "English",
    inStock: true,
  },
]
